package com.dinzeer.legendblade.regsitry.other;

import com.dinzeer.legendblade.data.LegendBuiltInRegsitry;
import com.dinzeer.legendblade.regsitry.slashblade.LBSpecialEffectsRegistry;
import mods.flammpfeil.slashblade.registry.slashblade.SlashBladeDefinition;
import mods.flammpfeil.slashblade.registry.specialeffects.SpecialEffect;
import net.minecraft.resources.ResourceKey;
import net.minecraftforge.registries.RegistryObject;

import static com.dinzeer.legendblade.Legendblade.MODID;
import static com.dinzeer.legendblade.Legendblade.REGISTRATE;

public class LangRegsitry {
    //增加语言键
    public static void registerAddlang(){
        REGISTRATE.addRawLang("item.legendblade.bloodkatana","bloodkatana");
        REGISTRATE.addRawLang("item.legendblade.godfox","god fox");
        REGISTRATE.addRawLang("item.legendblade.neogodfox","neo god fox");
        REGISTRATE.addRawLang("item.legendblade.nihilexfake","nihilex fake");
        REGISTRATE.addRawLang("item.legendblade.stickgodfox","stick god fox");
        REGISTRATE.addRawLang("item.legendblade.truegodfox","true godfox");
        REGISTRATE.addRawLang("item.legendblade.whitegodfox","white god fox");
        REGISTRATE.addRawLang("item.legendblade.rustgodfox","rust godfox");
        REGISTRATE.addRawLang("item.legendblade.shinku","shinku");
        REGISTRATE.addRawLang("item.legendblade.asmodeus","asmodeus");
        REGISTRATE.addRawLang("item.legendblade.asmodeusex","asmodeus ex");
        REGISTRATE.addRawLang("item.legendblade.beelzebub","beelzebub");
        REGISTRATE.addRawLang("item.legendblade.beelzebubex","beelzebub ex");
        REGISTRATE.addRawLang("item.legendblade.belphegor","belphegor");
        REGISTRATE.addRawLang("item.legendblade.belphegorex","belphegor ex");
        REGISTRATE.addRawLang("item.legendblade.evil","evil");
        REGISTRATE.addRawLang("item.legendblade.evilex","evilex");
        REGISTRATE.addRawLang("item.legendblade.foxex","foxex god fox");
        REGISTRATE.addRawLang("item.legendblade.foxex2","foxex soul fox");
        REGISTRATE.addRawLang("item.legendblade.foxexfinal","foxex final");
        REGISTRATE.addRawLang("item.legendblade.leviathan","leviathan");
        REGISTRATE.addRawLang("item.legendblade.leviathanex","leviathan ex");
        REGISTRATE.addRawLang("item.legendblade.lucifer","lucifer");
        REGISTRATE.addRawLang("item.legendblade.luciferex","lucifer ex");
        REGISTRATE.addRawLang("item.legendblade.mammon","mammon");
        REGISTRATE.addRawLang("item.legendblade.mammonex","mammon ex");
        REGISTRATE.addRawLang("item.legendblade.samael","samael");
        REGISTRATE.addRawLang("item.legendblade.samaelex","samael ex");
        REGISTRATE.addRawLang("item.legendblade.wujiu","wujiuex");
        REGISTRATE.addRawLang("item.legendblade.belphebubex","belphebubex");
        REGISTRATE.addRawLang("item.legendblade.waterex","water ex");
        REGISTRATE.addRawLang("item.legendblade.fireex","fire ex");
        REGISTRATE.addRawLang("item.legendblade.lightningex","lightning ex");
        REGISTRATE.addRawLang("item.legendblade.godbird","The Blade of the Divine Bird");
        REGISTRATE.addRawLang("item.legendblade.crimsoncherryex","crimson cherry ex");
        REGISTRATE.addRawLang("item.legendblade.amazedshine","amazed shine");
        REGISTRATE.addRawLang("item.legendblade.nihilulex","nihilul ex");
        REGISTRATE.addRawLang("item.legendblade.nihilbxex","nihilbx ex");
        REGISTRATE.addRawLang("item.legendblade.sevensword","seven sword");
        REGISTRATE.addRawLang("item.legendblade.administrator","administrator’s blade");
        REGISTRATE.addRawLang("item.legendblade.demonbird","demon bird");
        REGISTRATE.addRawLang("item.legendblade.ark","ark");
        REGISTRATE.addRawLang("item.legendblade.neo","neo");
        REGISTRATE.addRawLang("item.legendblade.dragon_fire","dragon fire");
        REGISTRATE.addRawLang("item.legendblade.dragon_ice","dragon ice");
        REGISTRATE.addRawLang("item.legendblade.dragon_lightning","dragon lightning");
        REGISTRATE.addRawLang("item.legendblade.foreverice","forever ice");
        REGISTRATE.addRawLang("item.legendblade.blaze","blaze");
        REGISTRATE.addRawLang("item.legendblade.zerogalaxy","zero galaxy");
        REGISTRATE.addRawLang("item.legendblade.zhuzi","zhuzi's blade");
        REGISTRATE.addRawLang("item.legendblade.truebloodfox","true blood fox");
        REGISTRATE.addRawLang("item.legendblade.eiily","eiily!");
        REGISTRATE.addRawLang("item.legendblade.zangetsu","zangetsu");
        REGISTRATE.addRawLang("item.legendblade.frog","ice frog");
        REGISTRATE.addRawLang("item.legendblade.fish","fish");
        REGISTRATE.addRawLang("item.legendblade.crowbar","crowbar");
        REGISTRATE.addRawLang("item.legendblade.undragon","undragon");
        REGISTRATE.addRawLang("item.legendblade.sangeex","sangeex");
        REGISTRATE.addRawLang("item.legendblade.nobleblade","noble blade");
        REGISTRATE.addRawLang("item.legendblade.itan","itan");
        REGISTRATE.addRawLang("item.legendblade.phantomofgods","phantomofgods");
        REGISTRATE.addRawLang("item.legendblade.starriverblade","star river blade");
        REGISTRATE.addRawLang("item.legendblade.shallot","shallot");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.desireblade),"desire blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.wonderblade),"wonder blade X");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.tensazangetsu),"tensazangetsu");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.tensazangetsured),"tensazangetsu red");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.breakarm),"break arm");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.allice),"all ice");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.fireiron),"fire iron");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.tensazangetsunomoon),"tensazangetsu nomoon");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.mrke),"ke‘s blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.hu),"hutao‘s blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.VoidSword),"void sword");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.dguoblade),"dguoblade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.xhar),"The Blade of Front Lighting");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Seele),"seele");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.bloodfoxex),"bloodfox ex");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.justicegun),"justice gun");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.SolemnLament),"solemn lament");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.iceblade), "ice blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.maxkimblade), "maxkimblade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Reversed), "§m§kReversed§ksh§r Solomon");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Dubhe), "Dubhe");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Megrez), "Megrez");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Mizar), "Mizar");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Phecda), "Phecda");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Hagen), "Hagen");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Alkaid), "Alkaid");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Fenrir), "Fenrir");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.White), "White star");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.matongcblade), "waterblade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.natureblade), "nature blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.beyondblade), "beyond blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blackcloud), "blackcloud");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.rustkingsowrd), "rustkingsowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.kingsowrd), "kingsowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.vanity), "vanity");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blade_diamond), "diamond sowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blade_iron), "iron sowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blade_gold), "gold sowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blade_stone), "stone sowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blade_wood), "wood sowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blade_netherite), "netherite sowrd");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.dimension), "dimension");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.dragonblade), "dragon blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.blackpixie), "blackpixie");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.kingblade), "kingblade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.kumasakura), "kuma sakura");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.magicblade), "magic blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.purplesblade), "purples blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.pseudosword), "pseudo sword");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.whitesword), "white sword");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.latent), "latent");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.vitex), "vitex");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.xblades), "x blade");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Timotheos), "Timotheos");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.superred), "super red");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.bujin_sword), "bujin sword");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.dios), "dios sword");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.ten_blades), "cross saber");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.metatron), "metatron");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.metatronx), "metatron -ex-");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Lemir), "Lemir");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Rafael), "Rafael");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Michael), "Michael");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Uriel), "Uriel");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Gabriel), "Gabriel");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Charlierex), "Charlierex");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Lemirex), "Lemirex");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Rafaelex), "Rafaelex");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Michaelex), "Michaelex");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Urielx), "Urielx");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Gabrielex), "Gabrielex");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.Charlier), "Charlier");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.zein), "zein");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.holy), "holy");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.temperance), "temperance");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.reflection), "reflection");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.solomon), "solomon");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.reverse_solomon), "reverse solomon");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.shirin), "Pain Blade 'Shirin'");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.everything_not_ending), "Endless Cosmos 'Starry Ornament'");
        REGISTRATE.addRawLang(createitemlang(LegendBuiltInRegsitry.from_local_tourist), "Blade of the Native Tourist");

        REGISTRATE.addRawLang("item_group.legendblade.legendbladeitem","lengend blade|item");
        REGISTRATE.addRawLang("item_group.legendblade.legendblade_slashblade","lengend blade|Slashblade");
        REGISTRATE.addRawLang("se.legendblade.bad_blood","bad blood");
        REGISTRATE.addRawLang("se.legendblade.blade_attack","blade attack");
        REGISTRATE.addRawLang("se.legendblade.blessing","blessing");
        REGISTRATE.addRawLang("se.legendblade.sin","Sin");
        REGISTRATE.addRawLang("se.legendblade.poison","poison");
        REGISTRATE.addRawLang("se.legendblade.feastful","feastful");
        REGISTRATE.addRawLang("se.legendblade.shackles","shackles");
        REGISTRATE.addRawLang("se.legendblade.resentment","resentment");
        REGISTRATE.addRawLang("se.legendblade.suppress","suppress");
        REGISTRATE.addRawLang("se.legendblade.endless","endless");
        REGISTRATE.addRawLang("se.legendblade.bloodthirsty","bloodthirsty");
        REGISTRATE.addRawLang("se.legendblade.blessingsummonsword","blessing summon sword");
        REGISTRATE.addRawLang("se.legendblade.summonsword","summon sword");
        REGISTRATE.addRawLang("se.legendblade.foxbling","fox bling");
        REGISTRATE.addRawLang("se.legendblade.terrifying_waves","terrifying waves drive");
        REGISTRATE.addRawLang("se.legendblade.liuli","liuli");
        REGISTRATE.addRawLang("se.legendblade.liulione","liuli Sword One");
        REGISTRATE.addRawLang("se.legendblade.lighting_sum","lighting sum");
        REGISTRATE.addRawLang("se.legendblade.fire_dancy","fire dancy");
        REGISTRATE.addRawLang("se.legendblade.endsakurateriseup","end sakura rise up");
        REGISTRATE.addRawLang("se.legendblade.theshine","the shine");
        REGISTRATE.addRawLang("se.legendblade.waveedgeriseup","wave edge rise up");
        REGISTRATE.addRawLang("se.legendblade.fragmentededge","fragmented edge");
        REGISTRATE.addRawLang("se.legendblade.ark","ark");
        REGISTRATE.addRawLang( "se.legendblade.hossword","hossword");
        REGISTRATE.addRawLang("se.legendblade.fire","fire!");
        REGISTRATE.addRawLang("se.legendblade.lightning","lightning!");
        REGISTRATE.addRawLang("se.legendblade.ice","ice!");
        REGISTRATE.addRawLang( "se.legendblade.icfbreaker","ice and fire breaker");
        REGISTRATE.addRawLang( "se.legendblade.bloodfox","blood fox");
        REGISTRATE.addRawLang( "se.legendblade.voidmaker","void maker");

        REGISTRATE.addRawLang("se.legendblade.fireiron","fire iron!");
        REGISTRATE.addRawLang( "se.legendblade.breakarm","break arm");
        REGISTRATE.addRawLang( "se.legendblade.allice","all ice");
        REGISTRATE.addRawLang("se.legendblade.eternal","eternal");
        REGISTRATE.addRawLang( "se.legendblade.need","need");
        REGISTRATE.addRawLang( "se.legendblade.maxsky","maxsky");
        REGISTRATE.addRawLang( "se.legendblade.rainbow","rainbow");
        REGISTRATE.addRawLang( "se.legendblade.shinening","shinening");
        REGISTRATE.addRawLang( "se.legendblade.darkgod","darkgod");
        REGISTRATE.addRawLang( "se.legendblade.zain","zain");
        REGISTRATE.addRawLang( "se.legendblade.endurancetower","endurancetower");
        REGISTRATE.addRawLang( "se.legendblade.sannight","san night");
        REGISTRATE.addRawLang( "se.legendblade.haiker","haiker");
        REGISTRATE.addRawLang( "se.legendblade.superme","super me");
        REGISTRATE.addRawLang( "se.legendblade.max","Extreme speed and ultimate swordsmanship");
        REGISTRATE.addRawLang( "se.legendblade.physics_department","physics department");
        REGISTRATE.addRawLang( "se.legendblade.physics_department_fly","physics department fly");
        REGISTRATE.addRawLang( "se.legendblade.solemn_mourning","solemn mourning");
        REGISTRATE.addRawLang( "se.legendblade.devastate","devastate");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Strength),"Strength");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Cold),"Cold");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Dawn),"dawn");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.ExtinctionOfProjectiles),"ExtinctionOfProjectiles");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.BreakAll),"BreakAll");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Dubhe),"Dubhe");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.DubheEX),"DubheEX");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Megrez),"Megrez");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.MegrezEX),"MegrezEX");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Mizar),"Mizar");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.MizarEX),"MizarEX");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Phecda),"Phecda");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.PhecdaEX),"PhecdaEX");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Hagen),"Hagen");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.HagenEX),"HagenEX");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Alkaid),"Alkaid");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.AlkaidEX),"AlkaidEX");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Fenrir),"Fenrir");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.FenrirEX),"FenrirEX");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.GoldBlade),"goldblade");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.NonePower),"NonePower");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.nofear),"nofear");

        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.HealIs),"HealIs");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.pure),"pure");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Aryadeva),"Aryadeva");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Justice),"Justice");

        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.OccupyingHeart),"Occupying Heart");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.SeizetheBlood),"SeizetheBlood");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.CompassionforTorture),"CompassionforTorture");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Theinescapableguilt),"Theinescapableguilt");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.HelplessRest),"HelplessRest");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.Anuntraceablehope),"Anuntraceablehope");
        REGISTRATE.addRawLang( createselang(LBSpecialEffectsRegistry.angory),"angory");

        REGISTRATE.addRawLang("slash_art.legendblade.heart_slash","all slash");
        REGISTRATE.addRawLang("slash_art.legendblade.heart_slashc","super attack");
        REGISTRATE.addRawLang("slash_art.legendblade.monster_power","monster power");
        REGISTRATE.addRawLang("slash_art.legendblade.prowess","prowess");
        REGISTRATE.addRawLang("slash_art.legendblade.phantom_thrust","phantom thrust");
        REGISTRATE.addRawLang("slash_art.legendblade.soul_lock","soul lock");
        REGISTRATE.addRawLang("slash_art.legendblade.thatcher","thatcher");
        REGISTRATE.addRawLang("slash_art.legendblade.hunger_absorption","hunger absorption");
        REGISTRATE.addRawLang("slash_art.legendblade.split_apart","split apart");
        REGISTRATE.addRawLang("slash_art.legendblade.greedy_grip","greedy grip");
        REGISTRATE.addRawLang("slash_art.legendblade.flurry","flurry");
        REGISTRATE.addRawLang("slash_art.legendblade.mpss","monster power summon sword");
        REGISTRATE.addRawLang("slash_art.legendblade.void_slash_plus","EXJudgementCut");
        REGISTRATE.addRawLang("slash_art.legendblade.thrust","EX thrust");
        REGISTRATE.addRawLang("slash_art.legendblade.sakura_endex","EX Sakura end");
        REGISTRATE.addRawLang("slash_art.legendblade.terrifyingwaves","terrifying waves drive");
        REGISTRATE.addRawLang("slash_art.legendblade.lighting_swordsex","lighting swordsex");
        REGISTRATE.addRawLang("slash_art.legendblade.fire_dance","fire dance");
        REGISTRATE.addRawLang("slash_art.legendblade.swordone","one sword");
        REGISTRATE.addRawLang("slash_art.legendblade.swordoneex","one sword EX");
        REGISTRATE.addRawLang("slash_art.legendblade.birdthrust","bird thrust");
        REGISTRATE.addRawLang("slash_art.legendblade.slashshine","slash shine");
        REGISTRATE.addRawLang("slash_art.legendblade.delete","delete");
        REGISTRATE.addRawLang("slash_art.legendblade.bloodbirdthrust","blood bird thrust");
        REGISTRATE.addRawLang("slash_art.legendblade.sevenbladeslash","seven blade slash");
        REGISTRATE.addRawLang("slash_art.legendblade.lightningsummonsword","lightning summonsword");
        REGISTRATE.addRawLang("slash_art.legendblade.firesummonsword","fire summonsword");
        REGISTRATE.addRawLang("slash_art.legendblade.icesummonsword","ice summonsword");
        REGISTRATE.addRawLang("slash_art.legendblade.hosswords","hos summon sword");
        REGISTRATE.addRawLang("slash_art.legendblade.moondrive","moondrive");
        REGISTRATE.addRawLang("slash_art.legendblade.frog_glaxy","frog glaxy");
        REGISTRATE.addRawLang("slash_art.legendblade.save_all","save_all");
        REGISTRATE.addRawLang("slash_art.legendblade.elbowstrike","elbowstrike");
        REGISTRATE.addRawLang("slash_art.legendblade.swordrain","swordrain");
        REGISTRATE.addRawLang("slash_art.legendblade.exmoondrive","ex moondrive");
        REGISTRATE.addRawLang("slash_art.legendblade.lastmoondrive","last moondrive");
        REGISTRATE.addRawLang("slash_art.legendblade.sommon_sword_sommonex","sommon sword sommonex");
        REGISTRATE.addRawLang( "slash_art.legendblade.sannight","san night");
        REGISTRATE.addRawLang("slash_art.legendblade.getthrust","let thrust");
        REGISTRATE.addRawLang("slash_art.legendblade.butterfly","butter fly");
        REGISTRATE.addRawLang("slash_art.legendblade.thrust_summon_sword","thrust summon sword");
        REGISTRATE.addRawLang( "slash_art.legendblade.allover","allover");
        REGISTRATE.addRawLang("slash_art.legendblade.star_edge","star edge");
        REGISTRATE.addRawLang("slash_art.legendblade.foever","foever");
        REGISTRATE.addRawLang("slash_art.legendblade.thrust_eex","thrust eex");
        REGISTRATE.addRawLang("slash_art.legendblade.dragon_boost","dragon boost");
        REGISTRATE.addRawLang("slash_art.legendblade.black_hole","black hole");
        REGISTRATE.addRawLang("slash_art.legendblade.kingblade","king blade");
        REGISTRATE.addRawLang("slash_art.legendblade.blackslash","blackslash");
        REGISTRATE.addRawLang("slash_art.legendblade.thrust_slash","thrust slash");
        REGISTRATE.addRawLang("slash_art.legendblade.thrust_slash_ex","thrust slash ex");
        REGISTRATE.addRawLang("slash_art.legendblade.wakeup","wake up");
        REGISTRATE.addRawLang("slash_art.legendblade.judgement_cut_exbig","judgement cut exbig");

        REGISTRATE.addRawLang("slash_art.legendblade.jusitce_slash","jusitce slash");
        REGISTRATE.addRawLang("slash_art.legendblade.ultra_slash","ultra slash");
        REGISTRATE.addRawLang("slash_art.legendblade.rot_slash","rot slash");
        REGISTRATE.addRawLang("slash_art.legendblade.heal_slash","heal slash");
        REGISTRATE.addRawLang("slash_art.legendblade.circleslashex","circleslashex");
        REGISTRATE.addRawLang("slash_art.legendblade.alloverex","alloverex");
        REGISTRATE.addRawLang("slash_art.legendblade.alloverex2","all over ex all");
        REGISTRATE.addRawLang("slash_art.legendblade.save_the_world","save the world");


        REGISTRATE.addRawLang("enchantment.level.15","XV");
        REGISTRATE.addRawLang("enchantment.level.10","X");
        REGISTRATE.addRawLang("enchantment.level.0","128");
        REGISTRATE.addRawLang("enchantment.level.128","128");
        REGISTRATE.addRawLang("enchantment.legendblade.sword_raw","sword art · summon sword");
        REGISTRATE.addRawLang("enchantment.legendblade.sword_raw.desk","Generate a tracking phantom sword with probability during attack");
        REGISTRATE.addRawLang("effect.legendblade.hit_damage","hit damage");
        REGISTRATE.addRawLang("effect.legendblade.strength_damage","strength damage");
        REGISTRATE.addRawLang("effect.legendblade.sumeru","sumeru");
        REGISTRATE.addRawLang("entity.legendblade.no_end","end king");


        REGISTRATE.addRawLang("message.seven_sword_cooldown","This SA has entered a cooling state, kill it %s to unlock it");
        REGISTRATE.addRawLang("se.legendblade.tooltip.sevensowrd.1","OFF");
        REGISTRATE.addRawLang("se.legendblade.tooltip.sevensowrd.2","you should kill one wither on open this blade");
        REGISTRATE.addRawLang("se.legendblade.tooltip.sevensowrd.3","ON");
        REGISTRATE.addRawLang("se.legendblade.tooltip.sevensowrd.4","That s Roll!");

    }


    public static String createitemlang(ResourceKey<SlashBladeDefinition> a){
        return "item."+MODID+"."+a.location().getPath();
    }
    public static String createselang(RegistryObject<SpecialEffect> a){
        return "se."+MODID+"."+a.getId().getPath();
    }
}
